### ISSUE TITLE
Add a `skip_every` iterator

### ISSUE THREAD

**Issue by shssoichiro** [rust-itertools/itertools#132]
The name and semantics can be changed if necessary, but I'd like an iterator that skips every `n`th element, and I wasn't able to find an existing one in reading through the docs. For example:

```
let items = vec![1, 2, 3, 4, 5, 6, 7, 8];
assert_eq!(vec![1, 2, 4, 5, 7, 8], items.iter().skip_every(3).collect());
```

**Comment by fyrchik** [comment]
This is equivalent to `.enumerate().filter(|(n,_)| n % 3 != 2).map(|(_,v)| v)`. (or just `enumerate` + `filter_map`. I am not sure if specific implementation will be faster.

**Comment by shssoichiro** [comment]
This ticket is from 3 years ago, so probably could be closed anyway. Thanks for alternative suggestion!
