### ISSUE TITLE
Enhancement: Coalesce-style functions

### ISSUE THREAD

**Issue by jethrogb** [rust-itertools/itertools#136]
I've used the following functions in two completely different unrelated projects already. They basically take an `Iterator<Result>` (or `Iterator<Option>`) and return the first `Ok` Result or the last `Err`.

``` rust
trait RetryIterator: Iterator {
    fn retry_results<T, E>(&mut self) -> std::result::Result<T, E> where Self: Iterator<Item=std::result::Result<T, E>> {
        let mut last=None;
        loop {
            let cur=self.next();
            match cur {
                Some(v @ Ok(_)) => { return v; },
                Some(e @ Err(_)) => { last=Some(e); },
                None => if let Some(e) = last { return e; },
            }
        }
    }

    fn retry_options<T>(&mut self) -> Option<T> where Self: Iterator<Item=Option<T>> {
        let mut last=None;
        loop {
            let cur=self.next();
            match cur {
                Some(v @ Some(_)) => { return v; },
                Some(e @ None) => { last=Some(e); },
                None => if let Some(e) = last { return e; },
            }
        }
    }
}

impl<T: Iterator> RetryIterator for T {}
```

I'm happy to turn this into PR but first wanted to discuss what would be the best way to implement this.

**Comment by bluss** [comment]
Is there some nice way to write these with just .fold_while?

**Comment by jethrogb** [comment]
Not really. Especially for `Result`, there is no good "init" value to pass into fold.

**Comment by bluss** [comment]
I'd implement them both with a for loop. There seems to be an error where the if let's else clause is not handled and leads to an infinite loop, and that would be resolved naturally with for.

Is there some way we could generalize these two so there's only one method called retry or something like that? Would be cool. Maybe some other instance of it falls out.

**Comment by jethrogb** [comment]
> Is there some way we could generalize these two so there's only one method called retry or something like that? Would be cool. Maybe some other instance of it falls out.
Maybe in the future with some form of the `Carrier` trait.

**Comment by jethrogb** [comment]
> I'd implement them both with a for loop. There seems to be an error where the if let's else clause is not handled and leads to an infinite loop, and that would be resolved naturally with for.

Is it ok to panic if the Iterator length is 0? That is kind of necessary for this API to work.

**Comment by bluss** [comment]
No I think panic on empty is a bit too tricky.

This could be a generalization:

```rust
    fn retry_until<F>(&mut self, mut f: F) -> Option<Self::Item>
        where F: FnMut(&Self::Item) -> bool,
    {
        if let Some(mut prev) = self.next() {
            if !f(&prev) {
                for elt in self {
                    prev = elt;
                    if f(&prev) {
                        break;
                    }
                }
            }
            Some(prev)
        } else {
            None
        }
    }
```

It would return `Option<Result>` and `Option<Option>>` for your cases respectively.
