### ISSUE TITLE
Implement IntoIterator<T> for MinMaxResult<T>?

### ISSUE THREAD

**Issue by BenoitZugmeyer** [rust-itertools/itertools#177]
I am using rust-itertools to solve [Advent Of Code](http://adventofcode.com) challenges, and today we had to write a recursive function to find the shortest and the longest paths in some kind of maze. So naturally, I went with `minmax_by_key`, and I found that using an iterator over `MinMaxResult` with `flat_map` would be a very elegant solution to compute the min and max recursively. Here is an example of what I would want to do:
```rust
fn find_paths(...) -> MinMaxResult<Vec<...>> {
    if ... { // end condition
        MinMaxResult::OneElement(path)
    } else {
        // compute next steps
        next_steps
            .iter()
            .flat_map(|step| {
                // ...
                find_paths(...).into_iter()
            })
            .minmax_by_key(|path| path.len())
    }
}
```
`.into_iter()` here would return an `Iterator<Item=Vec<...>>` , yielding items contained in the `MinMaxResult`. `Option` implements `IntoIterator`, so I guess it would be coherent to have this on `MinMaxResult` as well.

I am still a Rust beginner, but I managed to write a working implementation [here](https://github.com/BenoitZugmeyer/RustyAdventOfCode/blob/master/2016/src/bin/day17.rs#L12-L34), if you care to have a look.

In any case, I really like rust-itertools, keep up the good work!

**Comment by bluss** [comment]
Hi, thanks for the suggestion. That is pretty intriguing.

Converting to an iterator seems nice, but then the question is, can we do this without `IntoIterator`. Since MinMaxResult doesn't feel like a real iterable or have a natural sequence.

**Comment by BenoitZugmeyer** [comment]
`MinMaxResult` is comparable with `Option` with up to two values. Of course it have a more concrete semantic meaning, but in the end it's just a way to hold two optional values. `Option` is well integrated in the std lib and you usually don't need to use it's `IntoIterator` implementation. But imagine if `Iterator::filter_map` didn't exist: you could have the equivalent by using `Iterator::flat_map` in conjunction with `Option::into_iter`.

This is what I try to reproduce with my example. Another option would be to implement a set of methods on the Itertools trait to compare `MinMaxResult` items between them and returning a single `MinMaxResult` (ex: `compare_minmax`, `compare_minmax_by_key`, `compare_minmax_by`). That could be nice too, but maybe more limited.

**Comment by Philippe-Cholet** [comment]
With edition 2021 (in previous editions, `[T]::into_iter` yields `&T` items and no `T`s), a trick could be

    pub fn some_name<T>(minmax: MinMaxResult<T>) -> impl Iterator<Item = T> {
        match minmax {
            MinMaxResult::NoElements => [None, None],
            MinMaxResult::OneElement(unique) => [Some(unique), None],
            MinMaxResult::MinMax(min, max) => [Some(min), Some(max)],
        }.into_iter().flatten()
    }

While I appreciate the idea for AoC context, but I feel like it's too much a niche use for us to add.
