### ISSUE TITLE
Add rchunk()

### ISSUE THREAD

**Issue by LeopoldArkham** [rust-itertools/itertools#185]
It would be nice to have an `rchunk()` method that chunks an iterator starting from the end, preserving the internal order of the elements.

Pseudo-e.g: `[6, 2, 1, 5, 4, 9, 7, 8].rchunk(3)` would yield:
`[9, 7, 8] -> [1, 5, 4] -> [6, 2]`

If there's interest, I could get around to this later this month.

**Comment by bluss** [comment]
Hm, so that requires storing the whole chunk in a vec, so that it can be reversed.

**Comment by LeopoldArkham** [comment]
Yes. Either that or a wrapper around something like

```rust
let (first, rest) = it.split_at(it.len() % chunk_len);
first.chain(rest.chunks(chunk_len))
```
Haven't looked at the source, so I dunno what makes sense

**Comment by bluss** [comment]
It sounds like a solution from a more dynamic language, like Haskell. Our iterators don't have split_at, and we can't build recursive types without some indirection & overhead.

**Comment by Philippe-Cholet** [comment]
We either need to store the entire iterator in a vector (in which case it's not really in itertools scope but for slice methods implemented in std) or require the iterator to be `DoubleEndedIterator + ExactSizeIterator`.
I would rather improve the existing `chunk` than implement which seem to be of very little use.
