### ISSUE TITLE
Feature request: izip_all!

### ISSUE THREAD

**Issue by triptec** [rust-itertools/itertools#242]
I'm looking for something that if the lists are  of unequal length would extend the shorter ones with some defined default. I looked at the code for izip and realized that I've got no clue where to event begin..

**Comment by Philippe-Cholet** [comment]
Makes me think of `zip_longest` but with more iterators being zipped (because it seems to be a macro) and the `Item` type of each iterator requiring to be `Default`.
Since it is six years old, I'm closing this (unless I see some response).

**Comment by triptec** [comment]
@Philippe-Cholet Yes I agree it sounds like zip_longest. Well well =)
