### ISSUE TITLE
When to increase minimum rust version?

### ISSUE THREAD

**Issue by tobz1000** [rust-itertools/itertools#290]
The last time the minimum required version was bumped was rust-1.12.0, over a year
and a half ago. To my mind, a couple of developments make a good case for updating
the minimum compiler version pretty soon.

The first is `impl Trait`, which would be useful as a return type-specifier for
iterator adaptors. It would make their behaviour clearer without having to specify
what each adaptor yields in the documentation, and maye also allow for some changing
of return types between versions, without necessitating a breaking change. (Although
changing to `impl`-return types would be breaking change in the first place...)

The other upcoming feature is const generics. This could allow certain structures
to replace `Vec`s with arrays, when the user realistically will know how big their
iterator is; and could also replace some macro implementations, and use of dummy
arrays therein. Although realistically, this feature doesn't have a release date yet.

Are there any upcoming features in your mind which would make for a good reason
to upgrade?

Would you want to provide a "buffer" time, so that the minimum compiler version
isn't immediately the newest? (E.g. if updating to 1.27.0, wait until 1.29.0 is
released.)

**Comment by bluss** [comment]
Agreed that it is past time to update, but I think it is prudent to not update to the latest Rust version when that happens, but to an established, newer version. More similar to Rust 1.21 than Rust 1.28.
