### ISSUE TITLE
Interleave docs should point at izip! macro

### ISSUE THREAD

**Issue by gnzlbg** [rust-itertools/itertools#291]
The interleave docs should point at the izip macro: https://docs.rs/itertools/0.7.8/itertools/trait.Itertools.html#method.interleave

Bonus for the interleave docs to have an example that interleaves 3 iterators: https://play.rust-lang.org/?gist=438f0dce792bcc403312194ff926c7f0&version=stable&mode=debug

**Comment by gnzlbg** [comment]
This fails: https://play.rust-lang.org/?gist=5efe562e74e750008fffd8ca50a486e5&version=stable&mode=debug

```rust
#[macro_use] extern crate itertools;
use itertools::Itertools;
fn main() {
    let r: &[i32] = &[1, 1, 1, 1];
    let g: &[i32] = &[2, 2, 2, 2];
    let b: &[i32] = &[3, 3, 3, 3];

    let mut v: Vec<i32> = Vec::new();
    for &&i in izip!(r, g, b).flat_map(|(i,j,k)| [i,j,k].into_iter()) {
        v.push(i);
    }

    assert_eq!(&v, &[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]);
}
```

**Comment by gnzlbg** [comment]
mbrubeck proposed solving this using once: https://play.rust-lang.org/?gist=578e3e12d3c0af1bc9cdba3c31c018ed&version=undefined&mode=undefined

```rust
#[macro_use] extern crate itertools;
use itertools::Itertools;
use std::iter::once;

fn main() {
    let r: &[i32] = &[1, 1, 1, 1];
    let g: &[i32] = &[2, 2, 2, 2];
    let b: &[i32] = &[3, 3, 3, 3];

    let mut v: Vec<i32> = Vec::new();
    for i in izip!(r, g, b).flat_map(|(a,b,c)| once(a).chain(once(b)).chain(once(c))) {
        v.push(*i);
    }

    assert_eq!(&v, &[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]);
}
```

so maybe something like this should be shown with the `interleave` macro to show people how to interleave N iterators.

**Comment by bluss** [comment]
It's a solution that's understandable but it's not very pretty! We'd prefer to showcase something that actually fulfills its job well. Does this mean we need a better way to do n-ary interleaves?

**Comment by gnzlbg** [comment]
We might be able to come up with a macro that makes the code above nicer to write. I am also curious about how well the `chain` of `once`s compares to raw loop performance wise.

**Comment by bluss** [comment]
Subtle point is that a zip-based interleave ends sooner than the default interleave. A (length 4).interleave(length 3) iterator has a result of length 7. As usual, the n-ary version is only really nice as a function when we assume all input iterators have the same type (and can have them in a Vec). :worried:
