### ISSUE TITLE
Add Debug implementations where possible

### ISSUE THREAD

**Issue by fenhl** [rust-itertools/itertools#32]
I would like to use `MultiPeek` as part of a type which must be `Debug`. Currently I have to write a custom `Debug` implementation for this.

**Comment by bluss** [comment]
Yes, we can do this better. Unfortunately multipeek can't derive either, it depends on std::iter::Fuse. We'll solve it.

**Comment by bluss** [comment]
Not sure about the best way to solve this. libstd iterators don't impl Debug either, so even if we do, it won't be available very often.

Might have an impact on compile time & library size (metadata / generics part) with very little gain.

**Comment by bluss** [comment]
upstream libcore has Debug for iterators and adaptors now. the floodgates have opened!

**Comment by bluss** [comment]
It's a bit better in 0.5.5, lots of adaptors now have Debug. I ran out of steam to fix them all, so help wanted :smile:
