### ISSUE TITLE
Feature: combinations_with_replacement

### ISSUE THREAD

**Issue by niklasf** [rust-itertools/itertools#332]
Similar to [combinations](https://docs.rs/itertools/0.8.0/itertools/trait.Itertools.html#method.combinations), but allowing multiple clones of a single element in each iteration, like https://docs.python.org/3/library/itertools.html#itertools.combinations_with_replacement.

**Comment by Synthetica9** [comment]
Yes! I'm now using `multi_cartesian_product` for this, but this is unbearably slow once you get to any size.

**Comment by tommilligan** [comment]
@Synthetica9 @niklasf I implemented this in #340, please give it a try and let me know any feedback

**Comment by niklasf** [comment]
Thanks @tommilligan, looks great!
