### ISSUE TITLE
single?

### ISSUE THREAD

**Issue by phimuemue** [rust-itertools/itertools#334]
I find myself repeatedly in need of a function that determines if an iterator yields a single element.

I found a crate doing this: https://github.com/CAD97/rust-single and also [asked](https://github.com/CAD97/rust-single/issues/1) the maintainer if we should add this functionality to itertools. What do you think about this?

**Comment by bluss** [comment]
collect tuple can do this (using a singlet), but it makes sense to give it its own name.

**Comment by phimuemue** [comment]
Good point, thanks.

Still, I still do feel that - in case of failure - it might be advantageous to know the reason.

Do you think changing from `Option<...>` to `Result<..., CollectTupleErr>` (where `CollectTupleErr` is an `enum` with `Empty` and `TooMany`) is a viable option?

**Comment by bluss** [comment]
I think I recognize this discussion, not sure from which issue. Do you want to help maintain this crate?

**Comment by phimuemue** [comment]
Ah, I see that there was some previous discussion at https://github.com/bluss/rust-itertools/pull/233#issuecomment-342578731. So I think I'll revisit my use case and see if I really need a `Result` carrying additional information or if I can get away with an option.

As for the maintainership offer: Thank you for thinking of me, but I think I wouldn't make a good maintainer at the moment (having a full-time job and a time-consuming hobby), so I have to politely decline.

**Comment by phimuemue** [comment]
I just wanted to give an update on the `Option` vs `Result` issue here: In many uses cases, I would actually benefit if I got a `Result` telling me why `single` did not work out.

In particular, I often want to allow "no element or one element only", but not multiple elements.

I see that we do not really have methods returning `Result`, but we have e.g. `MinMaxResult` which may be a similarly special.

**Comment by phimuemue** [comment]
I just observed that we have `exactly_one`, which I can probably use. Though it offers the contents of the whole original iterator, its usage seems imho a bit worse than what was originally suggested in this issue.

Closing this for now, as it covers my basic request.

**Comment by phimuemue** [comment]
``
