### ISSUE TITLE
Itertools needs new maintainers

### ISSUE THREAD

**Issue by sheganinans** [rust-itertools/itertools#354]
There are plenty that are willing to help:

> @bluss I'd be interested in helping maintain itertools if you're still looking for someone. I'm a member of the [rustsim](https://github.com/rustsim) organization, a [regular contributor to nalgebra](https://github.com/rustsim/nalgebra/commits?author=jswrenn), and a drive-by contributor of API improvements to many libraries.

_Originally posted by @jswrenn in https://github.com/bluss/rust-itertools/pull/348#issuecomment-501296808_

**Comment by jswrenn** [comment]
Happy update: I'll be taking ownership of maintaining itertools! My first priority is going to be tackling the backlog of open PRs. :)

**Comment by Avi-D-coder** [comment]
@jswrenn If you ever want help, or more eyes for code reviews. I would be happy to help out.

**Comment by sheganinans** [comment]
Thanks! Glad to hear this is moving in the right direction. This should be a pretty significant improvement for the community!
