### ISSUE TITLE
Feature request: try_collect

### ISSUE THREAD

**Issue by jplatte** [rust-itertools/itertools#359]
I often find myself wanting to write

```rust
some_iter
    .map(Type::fallible_conversion)
    .collect()?
```

This requires a turbofish for `collect` though, because both `?` and `collect` are generic. In every case I've had, I wanted the `FromIterator` implementation for `Result`. A dedicated `try_collect` method that's only available for `Result` iterators would solve this.

**Comment by jplatte** [comment]
This should work:

```rust
fn try_collect<T, U, E>(self) -> Result<U, E>
where
    Self: Sized + Iterator<Item = Result<T, E>>,
    Result<U, E>: FromIterator<Result<T, E>>,
{
    self.collect()
}
```

**Comment by jplatte** [comment]
@bluss would a PR that adds this be accepted?

**Comment by jswrenn** [comment]
Yeah, I'd accept this!
