### ISSUE TITLE
multizip equivalent for unzip

### ISSUE THREAD

**Issue by owenthewizard** [rust-itertools/itertools#362]
It would be nice to have something similar to `izip!`/`multizip` for `unzip`, e.g. `A, B, C, D, A, B, C, D, ...` -> `([A, A, A, [...], B, B, B, [...], [...])`

**Comment by piegamesde** [comment]
There is the [unzip-n](https://docs.rs/unzip-n) crate for that purpose, maybe it can be merged into itertools?

**Comment by Boscop** [comment]
@piegamesde That would be nice!
