### ISSUE TITLE
Consider applying rustfmt to the code?

### ISSUE THREAD

**Issue by upsuper** [rust-itertools/itertools#368]
It seems that the code here doesn't follow the [Rust style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md). Maybe consider applying rustfmt and add CI step to enforce it?

I think that would make people more comfortable to contribute, as they wouldn't need to think about what code style should they use, and can just rely on the tool to figure out.

**Comment by jswrenn** [comment]
I agree with the premise that unclear formatting rules may be an obstacle for new potential contributors. However, my primary concern right now are _existing_ potential contributors. Itertools has a considerable backlog of pull requests, and I want to avoid creating additional work for these patient contributors!

I'll revisit this after cutting down the number of pending pull requests.

**Comment by jplatte** [comment]
@jswrenn How about adding a `.rustfmt.toml` with `ignore = "*"` until you're done dealing with the PR backlog? That would improve the workflow for people who have their editors set up to run `rustfmt` on save.

**Comment by jswrenn** [comment]
Great idea. Can you send in a PR? I'll accept it immediately.
