### ISSUE TITLE
iproduct! can't be used with more than 8 iterators

### ISSUE THREAD

**Issue by steven-joruk** [rust-itertools/itertools#384]
I expect it's not an itertools problem, but it might be worth adding to the documentation.

```rust
use itertools::iproduct;

fn main() {
    for p in iproduct!(0..1, 0..2, 0..3, 0..4, 0..5, 0..6, 0..7, 0..8, 0..9) {
        println!("{:?}", p);
    }
}
```

And the error message for anyone searching for an answer:

> the trait `std::iter::Iterator` is not implemented for `itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::cons_tuples_impl::ConsTuples<itertools::adaptors::Product<itertools::adaptors::Product<std::ops::Range<{integer}>, std::ops::Range<{integer}>>, std::ops::Range<{integer}>>, (({integer}, {integer}), {integer})>, std::ops::Range<{integer}>>, (({integer}, {integer}, {integer}), {integer})>, std::ops::Range<{integer}>>, (({integer}, {integer}, {integer}, {integer}), {integer})>, std::ops::Range<{integer}>>, (({integer}, {integer}, {integer}, {integer}, {integer}), {integer})>, std::ops::Range<{integer}>>, (({integer}, {integer}, {integer}, {integer}, {integer}, {integer}), {integer})>, std::ops::Range<{integer}>>, (({integer}, {integer}, {integer}, {integer}, {integer}, {integer}, {integer}), {integer})>, std::ops::Range<{integer}>>, (({integer}, {integer}, {integer}, {integer}, {integer}, {integer}, {integer}, {integer}), {integer})>`
>   = note: required by `std::iter::IntoIterator::into_iter`

**Comment by phimuemue** [comment]
Wouldn't it be possible to lift this restriction by changing https://docs.rs/itertools/0.8.1/src/itertools/cons_tuples_impl.rs.html#37 from

`impl_cons_iter!(A, B, C, D, E, F, G, H,);`

to

`impl_cons_iter!(A, B, C, D, E, F, G, H, I,);`?

**Comment by bluss** [comment]
It's an itertools problem but I think it is a reasonable one, shouldn't add too many more impls (they would be unused and still cost compile time).

**Comment by steven-joruk** [comment]
Okay, good to know. I can solve my problem in a different way, thanks.
