### ISSUE TITLE
Add pairwise()

### ISSUE THREAD

**Issue by Kinrany** [rust-itertools/itertools#388]
RxJS and python's itertools have `pairwise`. It's an operator that yields every consecutive pair. For example, `[1, 2, 3, 4]` will become `[(1, 2), (2, 3), (3, 4)`.

RxJS: https://rxjs.dev/api/operators/pairwise \
Python: https://docs.python.org/3/library/itertools.html (not linkable, please search for "pairwise")

I've already implemented it for my own use. I'd be happy to contribute a RP.

**Comment by jswrenn** [comment]
This sounds similar (equivalent?) to [`Itertools::tuples`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.tuples). Does that fit your use case?

**Comment by Kinrany** [comment]
@jswrenn no, they're similar but different:

```
tuples_2: [1, 2, 3, 4] -> [(1, 2), (3, 4)]
pairwise: [1, 2, 3, 4] -> [(1, 2), (2, 3), (3, 4)]
```

**Comment by jswrenn** [comment]
[`Itertools::tuple_windows`](https://docs.rs/itertools/0.8.2/itertools/trait.Itertools.html#method.tuple_windows)?

**Comment by Kinrany** [comment]
Indeed, thanks :)

**Comment by Kinrany** [comment]
I wonder if it would make sense to add pairwise to the docs, so that it's searchable?

**Comment by robinmoussu** [comment]
@Kinrany I think it does. I had the exact same issue, and I wasn't able to find it using the search engine of docs.rs, duckduckgo and google. If I didn't searched in the closed issue, I would have opened one. I created a PR, feel free to modify it ;)

**Comment by George-Ogden** [comment]
I know this was a while ago, but is it worth adding a pairwise method as a convenience function? It would also make the code more readable for people skimming existing Rust code.

**Comment by Kinrany** [comment]
As an alias for `tuple_windows` perhaps? That would make it searchable in docs.

**Comment by George-Ogden** [comment]
I think it would be nice if it could somehow restrict to a 2-tuple/pair, so that you can't write:
```rust
for (a, b, c) in my_list.pairwise() {
   ...
}
```

**Comment by George-Ogden** [comment]
@Kinrany I've opened #1111, do you think I should make any changes?

**Comment by phimuemue** [comment]
Closing as per https://github.com/rust-itertools/itertools/pull/1111#issuecomment-4779199918

**edit:** Thanks @Kinrany for bringing doc-alias to my attention.

**Comment by Kinrany** [comment]
> We lean towards not introducing new thin convenience wrappers.

@phimuemue very much agree, I was rather thinking of [rustdoc aliases](https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#alias) that allow looking up existing items by alternative names in documentation. Would that be more agreeable?

**Comment by jswrenn** [comment]
We'd be happy to accept a PR adding rustdoc aliases.
