### ISSUE TITLE
[RFC] `dedup()`/`dedup_by()` with count

### ISSUE THREAD

**Issue by orium** [rust-itertools/itertools#393]
Every once in a while I find myself re-implementing a "dedup with count", an iterator that instead of yielding `T` yields `(usize, T)`:

```rust
let data = vec![10, 10, 20, 30, 30, 30, 20];
assert_eq!(
    data.into_iter().dedup_with_count().collect(),
    vec![(2, 10), (1, 20), (3, 30), (1, 20)]
);
```

If you agree that these (`dedup_with_count()`/`dedup_by_with_count()`) are useful methods I can open a PR with the implementation soon.

**Comment by phimuemue** [comment]
This looks like a useful addition to me (I could not find anything similar in Itertools/Iterator).

Some thoughts:

* `(count, element)` or `(element, count)`? Any informed preferences?
* Maybe implementable via (generalizing) `DedupBy`/`CoalesceCore`?

**Comment by orium** [comment]
> (count, element) or (element, count)? Any informed preferences?

`(count, element)` makes more sense to me intuitively, but maybe only because I'm used to the output of `uniq -c`.  It also has the advantage that you can get the elements ordered by frequency by just doing `.dedup_with_count().sorted()` (assuming they are originally sorted).

> Maybe implementable via (generalizing) DedupBy/CoalesceCore?

I agree.  The overhead of counting should be negligible.

**Comment by gin-ahirsch** [comment]
> * `(count, element)` or `(element, count)`? Any informed preferences?

`(index, element)` is also the order of `Iterator::enumerate()`. While a slight semantic difference, it still looks consistent with that.

**Comment by danielhuang** [comment]
I am willing to work on this.

**Comment by orium** [comment]
I don't have the time for the next couple weeks or so to pick this up, so if you want to pick it up go ahead.

**Comment by orium** [comment]
@danielhuang I found myself with some time and implemented this.  I hope you don't mind.
