### ISSUE TITLE
no_std itertools and panic handlers do not work

### ISSUE THREAD

**Issue by AlexEne** [rust-itertools/itertools#409]
Hello,

I am trying to use itertools in a no_std project and I keep getting errrors about panic handlers being  declared  twice like the error below:

Error:  
```
➜  itertools_no_std git:(master) ✗ cargo build
   Compiling itertools_no_std v0.1.0 (itertools_no_std)
error[E0152]: duplicate lang item found: `panic_impl`.
  --> src/main.rs:8:1
   |
8  | / pub extern "C" fn panic(_info: &PanicInfo) -> ! {
9  | |     // A small trick that can save some size - tell the optimizer that this point is unreachable,
10 | |     // thereby allowing to to assume branches that panic never actually happen, which they
11 | |     // shouldn't in a release build. Obviously very unsafe, so you probably don't want this in
...  |
15 | |     }
16 | | }
   | |_^
   |
   = note: first defined in crate `std` (which `itertools` depends on).

error: aborting due to previous error
```
It seems that std is still brought in by itertools:  
> = note: first defined in crate `std` (which `itertools` depends on).

`error_handler`, `eh_personality` and `panic_hander` will all experience similar errors to the one above.

Example repro case:
```rust
#![no_std]
use itertools::Itertools;
use core::hint::unreachable_unchecked;
use core::panic::PanicInfo;

#[panic_handler]
#[no_mangle]
pub extern "C" fn panic(_info: &PanicInfo) -> ! {
    // A small trick that can save some size - tell the optimizer that this point is unreachable,
    // thereby allowing to to assume branches that panic never actually happen, which they
    // shouldn't in a release build. Obviously very unsafe, so you probably don't want this in
    // debug builds.
    unsafe {
        unreachable_unchecked()
    }
}

fn main() {
    let a = (0..).zip("bc".chars());
    let b = (0..).zip("ad".chars());
    let _it = a.merge_by(b, |x, y| x.1 <= y.1);
}
```

cargo.toml file:
```toml
[dependencies]
itertools="*"
```

Setting dependencies `itertools={ version="*", features=[]}` still produces the issue above.

As far as I understand from [the docs](https://docs.rs/itertools/0.8.2/itertools/#crate-features), itertools is compatible with a no_std environment.  
Is there something I am doing wrong?

**Comment by casept** [comment]
Have you tried setting `default-features=false` in your `Cargo.toml`? IIRC, the `features` declaration is additive, meaning that what you're actually telling Cargo is "concatenate this list of features with the default features", not "only use these features".

**Comment by AlexEne** [comment]
Seems to solve my issue. Will reopen if I find any more  problems. Thanks
