### ISSUE TITLE
Request for publish of latest version

### ISSUE THREAD

**Issue by giarc3** [rust-itertools/itertools#419]
I need functionality from https://github.com/rust-itertools/itertools/commit/649f2c2d09265b2b05be42d4e48bf89f5b03c476, but I cannot use `cargo publish` while depending on a git hash. 

Would you be willing to publish the latest version of the repo to crates.io?

**Comment by jswrenn** [comment]
I'll `cargo publish` tomorrow! Sorry for the delay.

**Comment by jswrenn** [comment]
[Published!](https://crates.io/crates/itertools/0.9.0)
