### ISSUE TITLE
travis pipeline is slow

### ISSUE THREAD

**Issue by meltinglava** [rust-itertools/itertools#425]
The pipline takes significant ammount of time. Think there is a better way of doing this.

- [x] 1. ~~run `cargo bench --no-run` insdead of `cargo bench` as they take a while and I suspect results are not looked at. Feel like benchmarking results are better run locally. Checking that they build would always be nice.~~ merged in #426 

- [ ] 2. Building on all platforms, while just running test, check, (fmt, clippy)... on one toolchain (stable or nightly)

- [x] 3. Add caching for builds and compiler. ref: https://docs.travis-ci.com/user/languages/rust/#dependency-management. Ref #429

**Comment by bluss** [comment]
I think it's time to migrate from travis-ci.org - they are closing down. Github Actions should be an ok replacement?

**Comment by jswrenn** [comment]
Agree completely.
