### ISSUE TITLE
HomogeneousTuple / TupleCollect for N > 4 ?

### ISSUE THREAD

**Issue by Boscop** [rust-itertools/itertools#428]
It would be useful to have HomogeneousTuple / TupleCollect for N larger than 4.
E.g. I often use it with `splitn` to avoid allocations, like:
```rust
s.splitn(N, pattern).collect_tuple()
```
instead of 
```rust
if let [/* ... */] = pattern.splitn(N, pattern).collect_vec().as_slice() {
	Some(/* ... */)
} else {
	None
}
```
And often my N is higher than 4.

**Comment by jswrenn** [comment]
I'll happily accept a pull request for this!
