### ISSUE TITLE
What happened to ZipSlices?

### ISSUE THREAD

**Issue by BillyDM** [rust-itertools/itertools#433]
Did something replace ZipSlices? Does izip! implement this now? I'm trying to create a library to process audio. The slices I use are guaranteed to be the same length, so it would be more efficient to only check one of the iterators on each loop and not both. Here is an example of something along the lines of what I want to achieve:

```Rust
for (left, right) in izip!(left_slice, right_slice) {

    // some expensive code that uses both iterators as inputs

    *left += result;
    *right += result;
}
```

Also, do you think it would be more efficient to do something like this? If I use lazy iterators to chain computations, will it be optimally unrolled by the compiler?
```Rust
let mut res = izip!(left_slice, right_slice).map(|left, right| //expensive calculation));
res.map(|left, right| // another expensive calculation);
res.map(|left, right| // another expensive calculation);

let (left, right): (Vec<_>, Vec<_>) = res.collect().unzip();
left_slice.copy_from_slice(&[left]);
right_slice.copy_from_slice(&[right]);
```

**Comment by BillyMessenger** [comment]
Or if I do something like this, will the compiler elid the counting iterator?
```Rust
let len = left_slice.len();
let left_slice = &mut left_slice[..len];
let right_slice = &mut right_slice[..len]; // panics if shorter than left_slice

for i in 0..len {

    // expensive calculation

    left_slice[i] += result;
    right_slice[i] += result;
}
```

**Comment by phimuemue** [comment]
According to https://github.com/rust-itertools/itertools/blob/417b85de6df98acc12b1638cb01f5f1670f72dcb/CHANGELOG.md, one should 

> use `.zip()` instead

**Comment by BillyMessenger** [comment]
Okay, thanks!

**Comment by bluss** [comment]
Std zip has the kind of optimizations you want now. Note it's for particular iterators, but the slice iterators are among them.
