### ISSUE TITLE
Missing impls on MapResults

### ISSUE THREAD

**Issue by Ten0** [rust-itertools/itertools#434]
It should have the same impls as [std::iter::Map](https://doc.rust-lang.org/std/iter/struct.Map.html), that is, `ExactSizeIterator`, `DoubleEndedIterator`,... but currently [only has `Iterator`](https://docs.rs/itertools/0.9.0/itertools/structs/struct.MapResults.html).

**Comment by Adenylatcyclase** [comment]
MapResult seems deprecated and replaced by MapOk which is a type defined as `pub type MapOk<I, F> = MapSpecialCase<I, MapSpecialCaseFnOk<F>>`
MapSpecialCase does implement ExactSizeIterator and DoubleEndedIterator if the Iterator you call map_ok (former map_result) on implements it.
https://github.com/rust-itertools/itertools/blame/573743a097c1701ef3bf8f82a8554a71bfbf0943/src/adaptors/map.rs#L48
Seems to be implemented 8 months ago.
