### ISSUE TITLE
Add assert_empty?

### ISSUE THREAD

**Issue by camsteffen** [rust-itertools/itertools#443]
I think this would be a useful addition.

```rust
pub fn assert_empty<I>(i: impl IntoIterator<Item = I>)
where
    I: Debug + PartialEq<I>,
{
    assert_equal(i, iter::empty::<I>());
}
```

Except it probably needs to have it's own error message implementation since "left" and "right" wouldn't make sense.

**Comment by Philippe-Cholet** [comment]
It makes me think of #731 as it would be `assert!(i.is_empty(), "error message")`.

The implementation would probably be (without `PartialEq<I>`):

    if let Some(item) = i.next() {
        panic!("Not empty, next was: {:?}", item); // or any error message
    }
But since there is no reaction to this and the implementation is simple enough, I'm closing this.
