### ISSUE TITLE
How to use `try_fold` in place of `fold_while`?

### ISSUE THREAD

**Issue by NoraCodes** [rust-itertools/itertools#469]
`fold_while` has been deprecated in favor of `try_fold`, and will eventually be removed ( #223 ). However, there is little documentation on how to actually do this in an idiomatic way.

For example, [this playground comparison](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=23c6327290f7a03503aa2ea5146b31e5) is the best I could do and it looks awful. The iterator finishing early isn't an error - it's a totally acceptable condition.

I'm sure there's a better way to do this, but it would be nice to document that in `fold_while` or, perhaps, in `try_fold` (I'll be happy to open a MR for that if someone can give me a good example.)

**Comment by scottmcm** [comment]
It's true that a different `impl Try` makes this much nicer -- I added one to libcore that's used internally to make things like this more readable:

https://github.com/rust-lang/rust/blob/515c9fa505e18a65d7f61bc3e9eb833b79a68618/library/core/src/iter/mod.rs#L373-L378

**Comment by NoraCodes** [comment]
Oh yeah, that's much nicer! Would we be amenable to including such a construct in `itertools` since it's such a common case?

**Comment by NoraCodes** [comment]
Actually, never mind, that's silly.

**Comment by jswrenn** [comment]
@NoraCodes I'll hold off on removing `fold_while` for the foreseeable future, at least until a more ergonomic alternative is available.

**Comment by NoraCodes** [comment]
Thank you :pray:

**Comment by jswrenn** [comment]
`fold_while` will be un-deprecated (and slightly optimized!) our next release (`0.10.0`) with #476.

**Comment by NoraCodes** [comment]
Awesome! The stdlib feature has been merged, too, so you can use that at least on nightly.

**Comment by scottmcm** [comment]
...and I now have https://github.com/rust-lang/rfcs/pull/3058 open to start moving it towards stabilization.

**Comment by scottmcm** [comment]
Stabilization is now approved, but it'll take until September 9th to reach stable, so there's still a few months before any more work can happen here.
