### ISSUE TITLE
more no_std support

### ISSUE THREAD

**Issue by zendurix** [rust-itertools/itertools#470]
Although itertools have no_std support it lacks implementations of most usfeful functions like collect_vec, sorted_by() etc in no_std mode. From my tests it seems that implementing it should be fairly easy, and I will try to contribute with solution.

**Comment by jswrenn** [comment]
What do you have in mind? `Vec` is not available in `#[no_std]` contexts.

**Comment by zendurix** [comment]
So add alloc as dependency while in no_std. Most programs that use no_std already use alloc

**Comment by zendurix** [comment]
This will require adding new feature `no_std` so alloc can be included only there, and change 
`#[cfg(not(feature = "use_std"))]` to `
#[cfg(feature = "no_std")]`

**Comment by jacobrosenthal** [comment]
I can assure you that most no_std programs do not use alloc

**Comment by zendurix** [comment]
Still I think alloc is most reasonable option here, however I am still a beginner so I don't know other good options.

**Comment by jswrenn** [comment]
> This will require adding new feature `no_std` so alloc can be included only there, and change
> `#[cfg(not(feature = "use_std"))]` to ` #[cfg(feature = "no_std")]`

That doesn't sound quite right to me. Crate features should add functionality, not remove it.

A better approach would be to add a `use_alloc` feature and change [this line](https://github.com/rust-itertools/itertools/blob/master/Cargo.toml#L41) to:
```
use_std = ["use_alloc"]
```
...and to change [this line](https://github.com/rust-itertools/itertools/blob/89f3a0dafc372786cacb91d0e30c97b1d9dcb2d9/Cargo.toml#L40) to:
```
default = ["use_alloc"]
```

(I don't think we currently use *any* std-only features, so this won't be a breaking change.)

@zendurix Are you actually programming in an environment that has `alloc` but not `std`?

**Comment by zendurix** [comment]
I am working on adding no_std feature to projekt, and I am already using alloc there. I think tomorrow (at my time) I will try to add and test this feature and if it works fine I will make PR. 
use_alloc feature sounds good, even nalgebra has feature alloc and propably many more
