### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by Veetaha** [rust-itertools/itertools#472]
Itertools seems to be 5 years old, but still < `1.0`. Are there any blockers for moving to the stable field?

**Comment by jswrenn** [comment]
There are no plans to move Itertools to 1.0. I see this crate as a place to experiment on ergonomic extensions to `Iterator`, and being free to make breaking changes to our API is occasionally a part of that. I would advise *against* using this crate's types as part of a crate's *public* API. Furthermore, whenever the methods on `Itertools` graduate to the standard library, we *need* to remove them from `Itertools`—this is always a breaking change.

In principle, of course, we could release a `1.0`, but I think it would send entirely the wrong message about `Itertools`.
