### ISSUE TITLE
Implement Send and Sync for Chunks

### ISSUE THREAD

**Issue by Koxiaet** [rust-itertools/itertools#480]
I need to use itertools' chunks in a multithreaded context but `IntoChunks: !Sync`, `Chunks: !Send + !Sync` and `Chunk: !Send + !Sync`. Is it possible to redesign them to allow this somehow?

**Comment by bluss** [comment]
They use Cell/RefCell for internal mutability - and they'd need to use thread safe primitives for that instead (at a slight/possible) performance cost.

**Comment by Koxiaet** [comment]
Ah, I see the problem. I originally opened this issue because I needed to use it in a `Send` async context, but I've fixed it now by moving the relevant code into a sync one (luckily I didn't need to hold a chunk over an await point). I'll close this since implementing it would add complexity and reduce performance.

**Comment by tqwewe** [comment]
I'm also having this issue sadly. Anything I can do to resolve this?

**Comment by Philippe-Cholet** [comment]
@tqwewe Above bluss' objection is still valid nowadays. Make a thread safe version would be quite some work.
And from my very little experience with it, I think it's not very fast to begin with (right?).
If you did solve this, we would surely consider merging your changes, but I don't think we would work on this.
