### ISSUE TITLE
Should 'ExactlyOneError' implement std-'Error'?

### ISSUE THREAD

**Issue by njam** [rust-itertools/itertools#482]
The `exactly_one()` function was added in https://github.com/rust-itertools/itertools/pull/310:
```rust
exactly_one(self) -> Result<Self::Item, ExactlyOneError<Self>> 
```

For using the early return operator `?` on its result, it would be nice if `ExactlyOneError` would implement `Error`. Or is there any reason not to?

cc @Xaeroxe @Centril @bluss

**Comment by Xaeroxe** [comment]
Fine by me

**Comment by jswrenn** [comment]
@njam Would you like to file a PR? This would be sufficient:
```rust
impl<I: Iterator> Error for ExactlyOneError<I> {}
```

**Comment by Xaeroxe** [comment]
I want to PR for a small change to the innards of the thing, so I'll get it.

**Comment by Xaeroxe** [comment]
See https://github.com/rust-itertools/itertools/pull/484

**Comment by tech6hutch** [comment]
I was just wanting this today, since the lack of Error impl makes ExactlyOneError not work well with `anyhow`. Is there any idea of when this enhancement will make it into the cargo version?

**Comment by jswrenn** [comment]
Thanks for poking me on this, @tech6hutch. I've been very busy. :( I'm going to try to chew threw the [remaining items in our release milestone](https://github.com/rust-itertools/itertools/milestone/2) this week.
