### ISSUE TITLE
fold_map_collect

### ISSUE THREAD

**Issue by cynecx** [rust-itertools/itertools#501]
Would something like a `fold_map_collect` be of interest for inclusion into itertools?

```rust
trait IteratorExt: Iterator {
    fn fold_map_collect<C, B, M, F>(self, init: B, mut f: F) -> (B, C)
    where
        F: FnMut(B, Self::Item) -> (B, M),
        C: Default + Extend<M>,
        Self: Sized,
    {
        let mut c = <C as Default>::default();
        let mut init = init;
        match self.size_hint() {
            (_, Some(upper)) => c.extend_reserve(upper),
            (lower, None) => c.extend_reserve(lower),
        }
        for item in self {
            let (new_init, mapped) = f(init, item);
            init = new_init;
            c.extend_one(mapped);
        }
        (init, c)
    }
}

impl<T: Iterator> IteratorExt for T {}
```

Example usage:

```rust
let (width, grid) =
    std::io::stdin()
        .lock()
        .lines()
        .fold_map_collect(0usize, |max_width, line| {
            let (line_width, line) = line.unwrap().chars().enumerate().fold(
                (0usize, 0u64), // (character count, encoded line)
                |(count, line), (idx, chr)| {
                    (
                        count + 1,
                        match chr {
                            '.' => line,
                            '#' => line | (1u64 << idx),
                            _ => panic!("invalid grid line"),
                        },
                    )
                },
            );
            (cmp::max(line_width, max_width), line)
        });
```

The name is bikesheddable.

**Comment by scottmcm** [comment]
My default instinct here is that combining this many different things is the wrong way to go.

This gives me a big of a `scan` vibe?  Is there a way to make an additional accessor on that?  Or a different kind of adapter that doesn't need to include the `collect` stuff too?

**Comment by cynecx** [comment]
> This gives me a big of a scan vibe? Is there a way to make an additional accessor on that?

You mean something like `scanl :: (a -> b -> a) -> a -> [b] -> [a]`? That wouldn't work because I need both the accumulator *and* mapped items returned. Both types might differ so it also not possible to just add the accumulator into the returned list.

> Or a different kind of adapter that doesn't need to include the collect stuff too?

I have though about this but can't find a way because fold map only doesn't work well together. `std` does include `unzip` but using that isn't "zero-cost" (because then I'd have to store the fold values for each entry and then stored them in a container, followed by the operation i want to do, eg. `max`).

I mean another thing you can do is just introduce a local and update the local each time you are trying to do your fold computation.

**Comment by SkiFire13** [comment]
Can't you just use an external variable with `map` and `collect`?

```rust
let mut max_width = 0usize;
let grid =
    std::io::stdin()
        .lock()
        .lines()
        .map(|line| {
            let (line_width, line) = line.unwrap().chars().enumerate().fold(
                (0usize, 0u64), // (character count, encoded line)
                |(count, line), (idx, chr)| {
                    (
                        count + 1,
                        match chr {
                            '.' => line,
                            '#' => line | (1u64 << idx),
                            _ => panic!("invalid grid line"),
                        },
                    )
                },
            );
            max_width = cmp::max(line_width, max_width);
            line
        })
        .collect();
```

**Comment by cynecx** [comment]
@SkiFire13 Well, yeh that would be possible, but I thought it would be nice to avoid state mutation ala Iterator::fold, but I guess this is such a niche case, it’d be much more readable with state mutation.

**Comment by emchristiansen** [comment]
I would find `fold_map_collect` to be quite useful, as:
1. I prefer to avoid mutation if I can, because it make it easier for me to reason about the code.
2. I can't use the external `mut` variable solution with my type (AFAICT), because the type isn't `Clone` nor `Copy` and the APIs which use the type expect to take it by value.

**Comment by emchristiansen** [comment]
Here's a concrete example of a case not covered by the `mut` variable pattern:

```rust
// Pretend this is a nontrivial type that isn't `Clone` nor `Copy`.
struct MyType
{
  x: i32,
  y: i32,
}

impl MyType
{
  // The API endpoints for this type consume it by value.
  pub fn set_x(
    self,
    x: i32,
  ) -> Self
  {
    Self { x, ..self }
  }
}

fn run() 
{
  let mut mytype = MyType { x: 1, y: 2 };
  let values = (0 .. 5).scan(
    mytype,
    |mytype, x| {
      let new_x = mytype.x + x;
      // To use the type, we need it by value, but we only have a reference and thus we cannot use it.
      // E.g. this next line fails to compile with error:
      // `cannot move out of `*mytype` which is behind a mutable reference`
      *mytype = (*mytype).set_x(new_x);
      Some(new_x)
    },
  );
}
```

Also I'd like to point out that the API of `fold_map_collect` is sufficiently canonical that it appears in [the `Base` library in OCaml](https://ocaml.org/p/base/latest/doc/Base/List/index.html#val-fold_map). Here it's called `fold_map`.

So, I think it's something that would make a lot of sense to have in the Rust ecosystem, specifically `itertools`.
