### ISSUE TITLE
iproduct! calls itself recursively with a local path, breaking syntax highlighting

### ISSUE THREAD

**Issue by grunweg** [rust-itertools/itertools#505]
I just found out that using the `iproduct!` macro [breaks syntax highlighting in rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/issues/6794). Clearly, this makes my development experience much worse. The reason is a long-standing bug in rust-analyzer, but fixing that will take time and effort.

In the meantime, this could be worked around by the macro calling itself like `crate::iproduct!` and not like `iproduct!` (see [here](https://docs.rs/itertools/0.9.0/src/itertools/lib.rs.html#233)). Are there any downsides to that (such as backwards compatibility)? Would you accept a patch doing this?

Thanks for making this crate; it has been really useful!

**Comment by grunweg** [comment]
Actually, syntax highlighting is not related to this issue. Hence, closing.

**Comment by lnicola** [comment]
While this doesn't break highlighting, it does cause problems when trying to call `itertools::iproduct` (without `use itertools::iproduct`) because the macro doesn't use `$crate` for the recursive expansions. I think it's a valid issue.
