### ISSUE TITLE
Product and MultiProduct should implement ExactSizeIterator if all the constituent iterators implement it

### ISSUE THREAD

**Issue by sunshowers** [rust-itertools/itertools#509]
Thanks for itertools! It's super useful :)

I do have one feature request: I love the Cartesian product iterators because they were just what I wanted for a use case, but I noticed that they're missing `ExactSizeIterator` implementations. I think the trait can be implemented if all the constituent iterators implement the trait.

I'd expect the result to be the product of the lengths of all the constituent iterators.

I'd be happy to submit a PR for this some time in the next couple of weeks if no one else gets to it. Thanks!

**Comment by scottmcm** [comment]
Because of the potential for overflow, it's not actually correct to implement `ExactSizeIterator` for any adapter that makes an iterator longer -- you'll notice that [`Chain`](https://doc.rust-lang.org/stable/std/iter/struct.Chain.html) doesn't implement it either.

**Comment by sunshowers** [comment]
Ah, good point. Could the TrustedLen contract be followed (or is it already followed)?

**Comment by SkiFire13** [comment]
That trait is unstable, so even if the contract could be followed, the trait itself can't be implemented

**Comment by sunshowers** [comment]
(yeah that's what I meant, just following the contract and documenting that it is followed)

**Comment by jswrenn** [comment]
`Product` *already* [overrides `size_hint`](https://docs.rs/itertools/0.10.0/src/itertools/adaptors/mod.rs.html#330-339), and [so does `MultiProduct`](https://docs.rs/itertools/0.10.0/src/itertools/adaptors/multi_product.rs.html#186-206).

**Comment by sunshowers** [comment]
It does, yes! So it looks like the only thing to do is to verify that the
impla follow the TrustedLen contract, update them if they don't, and
document that they do.

Rain
(they/she)
