### ISSUE TITLE
at_most_one

### ISSUE THREAD

**Issue by 1tgr** [rust-itertools/itertools#521]
There is [`exactly_one`](https://docs.rs/itertools/0.10.0/itertools/trait.Itertools.html#method.exactly_one) but no `at_most_one`. Is this a missing feature, or is it straightforward to replicate in terms of existing itertools functions?

**Comment by insideoutclub** [comment]
I would like to be assigned this issue, please. I have submitted a pull request that addresses it.
https://github.com/rust-itertools/itertools/pull/523
