### ISSUE TITLE
Add a note about how to permute with replacement

### ISSUE THREAD

**Issue by CraftSpider** [rust-itertools/itertools#524]
Currently, trying to get 'permutations with replacement', it's hard to find in the documentation how to do that. I eventually found on the github from the issue about adding permutations how `repeat_n(iter, iter.len()).multi_cartesian_product()` can do what I want, but it would be nice if this was mentioned in the docs, either on `permutations` or as a search alias on `multi_cartesian_product`.

Alternatively, it might be nice to have `permutation_with_replacement`, but I'm not sure if that's common enough that it's desired in the API.

**Comment by Raizex** [comment]
This was exactly what I needed as well, and was no where near obvious on how to achieve.

This is a very common use case, I would imagine, as it's a necessary step for computing the probability of rolling sum s on n dice and other similar probability calculations.
