### ISSUE TITLE
GroupingMap could allow aggregating into a non-HashMap or iteration

### ISSUE THREAD

**Issue by enterprisey** [rust-itertools/itertools#553]
It would be nice if a GroupingMap could be turned into something that wasn't a HashMap. I'd like to fold it into a Vec, for instance. Actually, maybe GroupingMap should implement `Iterator<Item = (K, Vec<V>)>`, or maybe even `Iterator<Item = (K, Iterator<Item = V>)>`.

**Comment by SkiFire13** [comment]
> It would be nice if a GroupingMap could be turned into something that wasn't a HashMap.

It has been proposed in the past for other methods, but IMO it's not that ergonomic unless we get default types for function generics. Maybe we could have a more generic version of each method while keeping the current ones? That still adds a lot of duplication though.

> Actually, maybe GroupingMap should implement Iterator<Item = (K, Vec<V>)>, or maybe even Iterator<Item = (K, Iterator<Item = V>)>.

The first one is specifically handled by `into_group_map`, the second one kinda handled with `GroupingMap::collect`.

In general I would be against exposing collecting operations as `Iterator`s, this gives the false perception that they are lazy, while in fact those operations are eager. If you really want to turn them into iterators just slap an `.into_iter()` after them.

**Comment by enterprisey** [comment]
> In general I would be against exposing collecting operations as `Iterator`s, this gives the false perception that they are lazy, while in fact those operations are eager. If you really want to turn them into iterators just slap an `.into_iter()` after them.

Oh, that's an excellent point that I completely missed.
