### ISSUE TITLE
Feature request: single.  

### ISSUE THREAD

**Issue by JCBurnside** [rust-itertools/itertools#566]
I propose two additional functions.

`fn single(self) -> Result<Self::Item, MutlipleResultError>` which will return Ok(Self::Item) if there is a single element in the iterator.

and 

`fn filter_single<F>(self, filter:F) -> Result<Self::Item, MutlipleResultError> where F: Fn(&Self::Item)->bool` which will be basically an alias for `self.filter(filter).single()`

Reasoning:
I am basing this off [C# linq's single function](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=net-5.0) which will throw an error if there is more than a single element in the enumerable.  There are cases where I want there to be a single element in the iterator and if multiple are found that is a logical error.

**Comment by phimuemue** [comment]
Hi! Isn't `single` the same as [`exactly_one`](https://docs.rs/itertools/0.10.1/itertools/trait.Itertools.html#method.exactly_one)? (To be fair, I think `single` may be a better name.)

As for `filter_single`, I do not know if this shortcut is worth an own function, as this rises the question why `filter` in connection with `single`/`exactly_one` is more special than e.g. `filter` with other functions. Is it a well known or very common pattern to do `filter().single()`?

**Comment by JCBurnside** [comment]
Welp I had missed exaclty_one when looking through the docs.   The `filter_single` is based of an overload of c#'s single which takes a function.

**Comment by scottmcm** [comment]
Note that Rust generally doesn't need the special-cased terminals the way C# does.  For example, C# has an `Enumerable.Count` overload that takes a predicate, but `.filter(p).count()` in Rust works well for that -- thanks to overloadable static dispatch, there's a special codepath to optimize for that combination: https://doc.rust-lang.org/1.45.0/src/core/iter/adapters/mod.rs.html#1012-1019

**Comment by JCBurnside** [comment]
I see.  Perhaps should consider a rename of `exactly_one` to `single`
