### ISSUE TITLE
collect_vec() doesn't compile in some cases where collect::<Vec<_>>() works

### ISSUE THREAD

**Issue by danielg1111** [rust-itertools/itertools#572]
Currently, it appears that `collect_vec()` can't be used in certain cases where `collect::<Vec<_>>()` works.  Is there any way this could be changed so that `collect_vec()` would work whenever `collect::Vec<_>>()` does?  

Here is one example where `collect::<Vec<_>>()` works, but `collect_vec()` doesn't compile:

```rust
use itertools::Itertools;
use rayon::prelude::*;

fn main() {
    let _foo = (0..42)
        .into_par_iter()
        .collect_vec();  // doesn't compile with collect_vec
        // .collect::<Vec<_>>();  // works when using turbofish instead of collect_vec()
}
```

Here's the full error message:

```
error[E0599]: the method `collect_vec` exists for struct `rayon::range::Iter<{integer}>`, but its trait bounds were not satisfied
  --> src\main.rs:7:10
   |
7  |         .collect_vec();  // doesn't compile with collect_vec
   |          ^^^^^^^^^^^ method cannot be called on `rayon::range::Iter<{integer}>` due to unsatisfied trait bounds
   |
  ::: C:\Users\Daniel\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-1.5.1\src\range.rs:48:1
   |
48 | pub struct Iter<T> {
   | ------------------
   | |
   | doesn't satisfy `rayon::range::Iter<{integer}>: Iterator`
   | doesn't satisfy `rayon::range::Iter<{integer}>: Itertools`
   |
   = note: the following trait bounds were not satisfied:
           `rayon::range::Iter<{integer}>: Iterator`
           which is required by `rayon::range::Iter<{integer}>: Itertools`
           `&rayon::range::Iter<{integer}>: Iterator`
           which is required by `&rayon::range::Iter<{integer}>: Itertools`
           `&mut rayon::range::Iter<{integer}>: Iterator`
           which is required by `&mut rayon::range::Iter<{integer}>: Itertools`

**Comment by sollyucko** [comment]
It looks like `rayon::range::Iter` doesn't implement `std::iter::Iterator`, but rather `rayon::iter::ParallelIterator`, which has its own `collect` method: https://docs.rs/rayon/1.5.1/rayon/iter/trait.ParallelIterator.html#method.collect

**Comment by scottmcm** [comment]
Sounds like this should be closed, then?

Traits aren't duck-typed, so making things that work on rayon traits is up to rayon, not itertools...

**Comment by jswrenn** [comment]
Yep! @danielg1111, consider suggesting that rayon add a `collect_vec` method to `ParallelIterator`. It *is* very convenient when `ParallelIterator` defines the same methods as `Itertools`.
