### ISSUE TITLE
Why `PeekingNext` does not provide `peek` method?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-itertools/itertools#583]
In my understanding, `PeekingNext` is a iterator from which we can obtain the reference to the next element.  Currently this trait requires `peeking_next` function, that consumes the next element when the predicate is satisfied.  But what if I want the `peek` behavior, in which the next element is *not* consumed?  I think it is reasonable to provide such trait method too.  Is there a reason that there isn't?

**Comment by jendrikw** [comment]
I think this can be implemented with something like this:

```rust
fn peek(&mut self) -> bool {
    let mut element;
    self.peeking_next(|x| {
        element = x;
        false
    });
    element
}
```

**Comment by TonalidadeHidrica** [comment]
I see, that's not really clean but it does work.  Thanks.

**Comment by jendrikw** [comment]
I agree that implementing `peeking_next` in terms of `peek` would be better.
