### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by multimeric** [rust-itertools/itertools#584]
There have been some new features added since 0.10.1, in particular I'm after [`multiunzip`](https://github.com/rust-itertools/itertools/pull/565). Would it be possible to publish a new release from the current master, given that there haven't been many changes recently?

**Comment by jswrenn** [comment]
Sure! I'll put one out tonight or tomorrow!

**Comment by phimuemue** [comment]
> Sure! I'll put one out tonight or tomorrow!

Prepared: https://github.com/rust-itertools/itertools/pull/585

**Comment by jswrenn** [comment]
Oops, I forgot that `cargo release` automatically bumps the version unless you tell it not to. Consequentially, I published 0.10.3. :sweat_smile:

We'll just fix up the change log accordingly for 0.10.4.
