### ISSUE TITLE
Extend k_smallest with largest and key options

### ISSUE THREAD

**Issue by orlp** [rust-itertools/itertools#586]
Currently this crate only has `k_smallest`. Compare this to the offering for `min`/`max` (which are the same function, just limited to k = 1):

```
position_max
position_max_by
position_max_by_key
position_min
position_min_by
position_min_by_key
```

I think it would be nice if we extended `k_smallest` to:

```
k_smallest
k_smallest_by
k_smallest_by_key
k_largest
k_largest_by
k_largest_by_key
```

**Comment by orlp** [comment]
If this has a good chance of being accepted I'm willing to make a pull request for this feature.

**Comment by phimuemue** [comment]
Sounds great to me!

If you decide to do a PR, could you try to implement `k_smallest` and `k_smallest_by_key` in terms of `k_smallest_by`? (So that the implementations are tied together and do not diverge.)

**Comment by jswrenn** [comment]
This has a great chance of getting merged! 🙂

**Comment by orlp** [comment]
Am I understanding it correctly that there's a bug in the current implementation?

https://github.com/rust-itertools/itertools/blob/master/src/k_smallest.rs#L10

This assumes the iterator is a `FusedIterator`, does it not?

**Comment by orlp** [comment]
Looking at it, I don't see a way we could implement this using `std::collections::BinaryHeap`, if we don't wish to duplicate the comparison function `k` times (and probably destroy inlining). I'm thinking of manually implementing the sifting logic, any thoughts on this?

**Comment by scottmcm** [comment]
> This assumes the iterator is a FusedIterator, does it not? I think we need to call .fuse() first?

Or skip the `for_each` if `heap.len() < k`.

**Comment by phimuemue** [comment]
> Looking at it, I don't see a way we could implement this using `std::collections::BinaryHeap`, if we don't wish to duplicate the comparison function `k` times (and probably destroy inlining). I'm thinking of manually implementing the sifting logic - mostly copying from the stdlib, any thoughts on this?

I guess your problem is that `BinaryHeap` does not support custom comparison functions by itself (please correct me if I'm wrong) - and I've come to the same conclusion when I once ran into this problem.

Copying the sifting logic might be a viable solution (unless it's a huge amount of code). I think we already did something similar, but I cannot find it. If you decide to go that route, please add a link to the source file you copied from, so that we can easily keep track of it.

**Comment by ejmount** [comment]
Hi, I've also been looking for this functionality, along with the ability to do `k_smallest` etc without allocations for statically determined k. I've been considering a PR that could incorporate both, but the logic would be reasonably complicated and potentially useful elsewhere, so would you have any preference about whether it could be published as a seperate crate and used here as a dependency or that it should be self-contained in this project? (I'd lean towards the former for aesthetic reasons - I couldn't see any similarly complicated supporting structures in the existing code)
