### ISSUE TITLE
only / single

### ISSUE THREAD

**Issue by gilescope** [rust-itertools/itertools#595]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=net-6.0

is there a way to do a filter and err if the result of the filter is not exactly one (ie error/none if not there or if many)? Quite often we want / expect that there is only one of something.

**Comment by phimuemue** [comment]
Do you know about 'exactly_one'? Using it, you could do 'iterative.filter(predicate).exactly_one()'?

**Comment by gilescope** [comment]
Apparently not :-) - many thanks!
