### ISSUE TITLE
feature request: tally

### ISSUE THREAD

**Issue by KisaragiEffective** [rust-itertools/itertools#599]
I think it is useful in some certain case:
```rs
let my_entries = vec!["A", "B", "C", "A", "C", "C"];
let tally = my_entries.iter().tally();
assert_eq!(tally.get("A").unwrap() == 2);
assert_eq!(tally.get("B").unwrap() == 1);
assert_eq!(tally.get("C").unwrap() == 3);
```

**Comment by scottmcm** [comment]
So you can do this with <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2bbeeafdec621ffe9e8bb5d4daab1b37>
```rust
let my_entries = vec!["A", "B", "C", "A", "C", "C"];
let foo = my_entries
    .into_iter()
    .map(|x| (x, ()))
    .into_grouping_map()
    .fold(0, |x, _, ()| x + 1);
dbg!(foo);
```

So maybe it would make sense to have a `count` on [`GroupingMap`](https://docs.rs/itertools/latest/itertools/structs/struct.GroupingMap.html), like there's already `min` and `product` and such.  (Conveniently, that'd also be a pretty small change.)

**Comment by phimuemue** [comment]
@scottmcm is right, but - if I'm not mistaken - [`counts`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.counts) already exists as a shorthand.

**Comment by KisaragiEffective** [comment]
@phimuemue wrote:
> @scottmcm is right, but - if I'm not mistaken - [`counts`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.counts) already exists as a shorthand.

Thanks! That's what I wanted!

**Comment by scottmcm** [comment]
Oh, I'd only looked at `GroupingMap` -- didn't even look at `Itertools` itself 🤦
