### ISSUE TITLE
Why `itertools` is not part of STD?

### ISSUE THREAD

**Issue by Wandalen** [rust-itertools/itertools#617]
Crate `itertools` implements a lot of useful and often essential algorithms based on pattern iterator, extending STD.
Why is it not part of STD?
Is there reason why it should be not a part of STD?
Is that harmful to have in STD something what is not totally necessary?

**Comment by scottmcm** [comment]
I suggest closing this issue, since it's not really specific enough to ever close, and the OP also asked it in a URLO thread: https://users.rust-lang.org/t/why-itertools-is-not-part-of-std/76016/27?u=scottmcm

To copy my reply to here:

> The core answer is that `itertools` can make breaking changes, but `std` cannot.
> 
> That means that anything we add to `Iterator` we're stuck with in exactly that form *forever*.  And since most of the provided things have no need to be overridden, there's no *need* to have them in `core`, so they might as well be in another crate if there's any question about it.
> 
> One common situation where that happens is things that might want lending iterators (formerly streaming iterators) in the future.  For example, `group_by` says
> 
> > This type implements [ `IntoIterator` ](https://doc.rust-lang.org/nightly/core/iter/traits/collect/trait.IntoIterator.html) (it is **not** an iterator itself), because the group iterators need to borrow from this value. It should be stored in a local variable or temporary and iterated.
> 
> So it's plausible that `std` doesn't want that right now, because it wants to leave the API space available for something that *can* be a (lending) iterator, once such a thing is possible.
> 
> Also, a bunch of the `itertools` things need extra types, not just the method on iterator.  Things like `MinMaxResult` and `EitherOrBoth` are important for making some of them work, but it's not clear that `core` wants to have those.

**Comment by jswrenn** [comment]
That's an excellent answer! I also want to add: Things in `itertools` sometimes _do_ make their way over to `libcore`! If I had my druthers, it'd happen more often. Unfortunately, because `itertools` is so widely used, adding methods with the same name to `Iterator` can cause [widespread breakage](https://github.com/rust-lang/rust/issues/88967).
