### ISSUE TITLE
An adapter to go from `&Result<T, E>` to `Result<&T, &E>`

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-itertools/itertools#621]
Many adapters require the `Result` type. However, sometimes you get `&Result` or `&mut Result` from e.g. `iter()` or `iter_mut()`. You can fix that with a simple `map()`, but I think an adapter to do that will be a good idea.

I'm not sure about the naming: `result_by_ref()` and `result_by_ref_mut()` is the best I can come up with. Also, I'm not sure if we also should include an adapter for `Option`. Any feedback?

**Comment by scottmcm** [comment]
I don't think itertools needs to have this -- `.map(Result::as_ref)` seems perfectly acceptable to me.

**Comment by ChayimFriedman2** [comment]
Haven't though about this one. +1
