### ISSUE TITLE
unique_by used with a reference to Self::Item

### ISSUE THREAD

**Issue by nklhtv** [rust-itertools/itertools#626]
Hi, I am trying to avoid cloning data while using unique_by and returning a reference to Self::Item, but there is an issue with the lifetimes.
How can i do that?

```Rust
use itertools::Itertools;

#[derive(Debug, PartialEq)]
struct Foo(pub String);

fn main() {
    let data = vec![Foo("1".to_owned()), Foo("3".to_owned()), Foo("3".to_owned())];
    itertools::assert_equal(data.into_iter().unique_by(|foo| &foo.0),
                        vec![Foo("1".to_owned()), Foo("3".to_owned())]);
}
```

**Comment by Philippe-Cholet** [comment]
For the lifetimes to be valid, one way is to not consume `data` with `data.iter()`.

    use itertools::Itertools;

    #[derive(Debug, PartialEq)]
    struct Foo(pub String);

    fn main() {
        let data = vec![Foo("1".to_owned()), Foo("3".to_owned()), Foo("3".to_owned())];
        itertools::assert_equal(data.iter().unique_by(|foo| &foo.0),
        //                           ~~~~                  now valid
                            vec![&Foo("1".to_owned()), &Foo("3".to_owned())]);
        //                       ~                     ~
    }

It's more about lifetimes than itertools, so I'm closing this for now. It might be unclosed if needed.
