### ISSUE TITLE
What's the real MSRV for itertools?

### ISSUE THREAD

**Issue by cuviper** [rust-itertools/itertools#636]
Currently, `itertools` documents MSRV 1.32, but CI only tests 1.36.

https://github.com/rust-itertools/itertools/blob/7a274080e01ffbe480fda96ce35600807f759974/.github/workflows/ci.yml#L11-L19

The `"use_alloc"` feature does need Rust 1.36 for stable `alloc`. However, even with bare `--no-default-features`, Rust 1.32.0 fails on calls to `checked_pow` and `saturating_pow`, which were both stabilized in 1.34.

I ask because I'm considering MSRV 1.36 for the `either` crate to implement `Future`, bluss/either#77, but I don't want to cause headaches if `itertools` actually wants to stay on an older MSRV.

**Comment by jswrenn** [comment]
It's just a documentation issue. Feel free to increase the MSRV of either to 1.36.
