### ISSUE TITLE
0.10.4 broken compatibility with Rust 1.48

### ISSUE THREAD

**Issue by davidhewitt** [rust-itertools/itertools#645]
https://docs.rs/crate/itertools/0.10.4/source/Cargo.toml contains a `resolver` key, which was not stable on Rust 1.48 and causes build errors.

`Cargo.toml.orig` does not contain the key, so this was probably caused by releasing with a nightly or beta toolchain which contains the bug https://github.com/rust-lang/cargo/issues/10954

Would you please be willing to re-release as 0.10.5 with an updated Cargo toolchain?

**Comment by phimuemue** [comment]
Hi, thanks for the report.

@jswrenn I'm no expert on what `cargo publish` internally does, but I tried a `--dry-run` with `cargo 1.63.0`, and it seems that it actually does not generate the `resolver` key in `Cargo.toml`. I pushed https://github.com/rust-itertools/itertools/commit/d61d12e808c8691eb0a672d3f9b65560be970a44 - maybe you can `cargo publish` it?

**Comment by phimuemue** [comment]
@davidhewitt Does the problem persist in 0.10.5?

**Comment by adamreichold** [comment]
Looking at 0.10.5 via the sources view of docs.rs [1] and comparing it to 0.10.4 [2], this looks resolved to me.

[1] https://docs.rs/crate/itertools/0.10.5/source/Cargo.toml

[2] https://docs.rs/crate/itertools/0.10.4/source/Cargo.toml

**Comment by adamreichold** [comment]
CI using Rust 1.48 also looks good now. [1] I'd say this is resolved.

[1] https://github.com/PyO3/pyo3/actions/runs/3239818816/jobs/5309679489

**Comment by davidhewitt** [comment]
Yep, thanks very much for fixing!
