### ISSUE TITLE
Changelog is missing for 0.10.3 and 0.10.5

### ISSUE THREAD

**Issue by ArekPiekarz** [rust-itertools/itertools#647]
When you look at [CHANGELOG.md](https://github.com/rust-itertools/itertools/blob/master/CHANGELOG.md), it does not contain entries for releases 0.10.3 nor 0.10.5. Is it possible to fill them to know what was added, modified or removed?

**Comment by phimuemue** [comment]
Hi there, thanks for the hint. Done in https://github.com/rust-itertools/itertools/commit/2106291a3b56a2951f7d0c459afddf7c28f7b1f4.
