### ISSUE TITLE
converting Vec<Vec<u8>> to Vec<u8>

### ISSUE THREAD

**Issue by bobi6666** [rust-itertools/itertools#655]
Hello, I would like to ask if itertools includes something like flat_map? because I would need to convert Vec<Vec<u8>> so that at the end it becomes Vec<u8> but with the fact that between each iteration a separator would be inserted, for example 47, which represents the character / and it would be a delimiter.

**Comment by scottmcm** [comment]
Can you show what you're doing, and how it works with, say, <https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.format> or <https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.intersperse> today?

**Comment by bobi6666** [comment]
thanks i used intersperse and converted Vec<Vec<u8>> to Vec<u8> like that:
let final_vec: Vec<u8> = itertools::intersperse(temp_vec.into_iter(),
Vec::from("/"))
.flatten()
.chain(once(0))
.collect();
i hope it is the best step i can do about performance

2022-11-09 7:53 GMT+01:00, scottmcm ***@***.***>:
