### ISSUE TITLE
using itertools::Tuples with rayon

### ISSUE THREAD

**Issue by bobi6666** [rust-itertools/itertools#659]
hello, I would like to use rayon::Tuples with rayon into_par_iter, could you tell me how it would be possible to provide an example of how to implement it?

**Comment by Philippe-Cholet** [comment]
It's more about rayon than itertools but I think the general solution to this is `par_bridge`.

    use itertools::Itertools;
    use rayon::prelude::*;

    fn main() {
        let v: Vec<_> = (0..1000)
            .tuples()
            .par_bridge()
            .map(|(x, y)| x + y)
            .collect();
        println!("{:?}", v);
    }
