### ISSUE TITLE
Add a method that converts a `Self::Item: AsRef<Path>` iter to a `Self::Item = std::io::Result<File>` iter

### ISSUE THREAD

**Issue by LikeLakers2** [rust-itertools/itertools#726]
Hi there!

I want to suggest a new method. This method would be usable on any iter where `Self::Item: AsRef<Path>`, and would spit out an iter where `Self::Item = std::io::Result<File>`.

I imagine the API looking like this:

```rust
use std::io::Result as IoResult;
use std::fs::{File, OpenOptions};
use std::path::Path;

// this has been split into multiple lines for ease of reading
fn open_files(self, options: OpenOptions)
-> impl Iterator<Self::Item = IoResult<File>>
where Self::Item: AsRef<Path>;
```

The returned iterator, which I'll call `OpenFiles` for now, would work as follows: For each `.next()` call, it will call `.next()` on the inner iterator, convert the returned item to a `Path`, and pass that path to `options.open()`. The resulting `std::io::Result<File>` would be returned.

Its primary use case is with inputs where you want to take in a file list, such as in command line applications that may take in multiple file paths as part of their arguments.

Caution should be used when operating with `OpenFiles` - if passed untrusted input (such as input from a website form), it may open files that you may not want it to open. However, this is an issue that would already need to be solved even without `OpenFiles` - all `OpenFiles` does is open the file for you as you iterate through a list of file paths.

Still, I believe this iterator may be useful, so I want to suggest it. If this iterator is desired, I may be open to making a PR (though no guarantees).

**Comment by scottmcm** [comment]
Can you elaborate on why this particular operation on paths is worth having as a specific iterator, rather than using `.map(|p| options.open(p))` or similar?

**Comment by LikeLakers2** [comment]
@scottmcm I'll admit that the reasoning I have isn't great - as you pointed out, using `.map()` or similar would be just as good.

That said, the reason I suggested this is because I believe opening a list of files (i.e. a `Vec<PathBuf>` handed to you by the `clap` crate) may be a common enough operation to reasonably want a one-liner - even if it only saves a couple lines of code.

Still, if you don't believe this reasoning is enough, I totally understand if you want to decline adding this suggestion.

**Comment by jswrenn** [comment]
My gut feeling is that `.map(|p| options.open(p))` is sufficiently short to not justify adding an `open_files` shorthand.
