### ISSUE TITLE
Feature request: .is_empty()

### ISSUE THREAD

**Issue by ijackson** [rust-itertools/itertools#731]
I keep finding myself writing things like `sometype.wombats().next().is_some()`.  (`.count()` is wrong because it walks the whole iterator; `.any(|_| true)` would be an alternative.

Maybe there should be `.is_empty()`  or something?  I'm not sure about the name.  It would have to *consume* the iterator and since `&mut I` is an iterator, maybe it should have a name that more clearly implies that it eats something.

**Comment by Philippe-Cholet** [comment]
First, I'm no maintainer here.
I think that the name `is_empty` implies it does not mutably change the iterator just like `Vec::is_empty` do not mutably change it. So `next_is_none`? Or `nothing_next`? I think `next` clearly suggest it consume one item.

    fn some_name(&mut self) -> bool {
        self.next().is_none()
    }
I'm not sure it is that important, and if not accepted, you can still do your own super-trait of Iterator.

**Comment by LikeLakers2** [comment]
A couple of notes here:

First off, any iterator that implements [`FusedIterator`](https://doc.rust-lang.org/std/iter/trait.FusedIterator.html) is guaranteed to continue returning `None` after it returns `None` once (assuming the iterator isn't just implementing `FusedIterator` willy-nilly. From the docs:

> Calling next on a fused iterator that has returned None once is guaranteed to return [None](https://doc.rust-lang.org/std/option/enum.Option.html#variant.None) again.

Second off, any iterator that implements [`ExactSizeIterator`](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html) already has a method to determine if it's empty. Currently, `ExactSizeIterator.is_empty()` is behind a nightly feature - but you can just as easily use `ExactSizeIterator.len() == 0`.

To be clear: I'm not against the inclusion of `.is_empty()` into `itertools` - however, I feel the above suggestion (a "is next item None?" method) may be a better inclusion, as it's something that can encompass iterators that don't know their size (or which may randomly return `None`).

**Comment by LikeLakers2** [comment]
@jswrenn Well, `.next().is_none()` would advance the iterator. Perhaps if `next_is_none()` peeks at the next item instead of consuming it, it'd be a nice addition?

**Comment by jswrenn** [comment]
In general, it's impossible to know whether an iterator is empty without advancing it.

**Comment by ijackson** [comment]
> In general, it's impossible to know whether an iterator is empty without advancing it.

That's why I proposed that `.is_empty()` should consume it.  But never mind, there is clearly too much opposition.

**Comment by jswrenn** [comment]
Does `.next().is_none()` satisfy your use-case?

**Comment by ijackson** [comment]
> Does `.next().is_none()` satisfy your use-case?

Let me quote my initial message

> I keep finding myself writing things like `sometype.wombats().next().is_some()`.  [...]
> 
> Maybe there should be `.is_empty()` or something?

In other words: I find `.next().is_some()` reads oddly and is clumsy.
