### ISSUE TITLE
Feature request: Implement DoubleEndedIterator for MergeBy if the source iterators implement DoubleEndedIterator

### ISSUE THREAD

**Issue by frankdavid** [rust-itertools/itertools#749]
The current implementation of `next()` makes use of `Peekable`. Both iterators get peeked and a comparator is used to decide which element is picked / which iterator gets advanced.

The main difficulty when implementing `next_back()` for `DoubleEndedIterator` would be that `Peekable` only allows peeking the front and not the back. The [MergeBy](https://docs.rs/itertools/latest/src/itertools/adaptors/mod.rs.html#516) struct would either manually have to store the front and back peeked values or use a data structure like [DoubleEndedPeekable](https://docs.rs/double-ended-peekable/latest/double_ended_peekable/struct.DoubleEndedPeekable.html).

If we could peek the back, the rest of the implementation would be straightforward, only the comparator's return value would need to be negated when iterating from the back.

**Comment by Philippe-Cholet** [comment]
There is some work of mine in #736 that would change the internal behavior from `peekable` to `put_back` but that does not change the fact it only looks at the front and not the back. I guess it would need some `DoubleEndedPutBack`.
