### ISSUE TITLE
Use `cargo-semver-checks` to prevent accidental breaking changes.

### ISSUE THREAD

**Issue by jswrenn** [rust-itertools/itertools#757]
We should consider using [cargo-semver-checks-action](https://github.com/obi1kenobi/cargo-semver-checks-action) to prevent accidental breaking changes.

**Comment by DavidCoy77** [comment]
Hi! I'd love to get started contributing to Rust, but I'd need a little help getting started since this would be my first ever GitHub contribution. I've tinkered around in RustRover so I'm eager to get to work if you're willing to help me out. Thanks!

**Comment by Philippe-Cholet** [comment]
@DavidCoy77 I don't know if #784 resolves this issue but Owen-CH-Leung is working on it.
