### ISSUE TITLE
`cargo test --all-targets` fails

### ISSUE THREAD

**Issue by warren2k** [rust-itertools/itertools#768]
At least, it fails with toolchain version 1.72.1

**Comment by Philippe-Cholet** [comment]
`thread 'main' panicked at 'attempt to add with overflow', benches\bench1.rs:584:19`

    fn kmerge_tenway(c: &mut Criterion) {
        let mut data = vec![0; 10240];
        let mut state = 1729u16;
        fn rng(state: &mut u16) -> u16 {
            let new = state.wrapping_mul(31421) + 6927; // <----
            *state = new;
            new
        }
        for elt in &mut data {
            *elt = rng(&mut state);
        }
        // ...

That seems to be quite old code. Investigating further...

**Comment by warren2k** [comment]
Looking further into this, it seems there's no attempt to run this in CI. Maybe this is not an issue.

**Comment by Philippe-Cholet** [comment]
It is added in #101 (in feb. 2016): https://github.com/rust-itertools/itertools/pull/101/files#diff-5e88c455e47e41d2006104fe8795309466144a7dc0b25f98632e7b85ec90b866R674
I ran `cargo test --bench bench1` on old commits (like a year ago and more) and got the same error.
That's definitely weird, good catch anyway.

**Comment by Philippe-Cholet** [comment]
Running the associated bench `cargo bench "kmerge tenway"` is fine though. I don't understand.

...Oh... bench uses `release` profile so it's silently ignored: `wrapping_add` would fix this I guess.
