### ISSUE TITLE
Guaranteeing health of the default branch

### ISSUE THREAD

**Issue by warren2k** [rust-itertools/itertools#769]
We just reported #768. How did failing code reach the default branch?

**Comment by mightyiam** [comment]
As was mentioned in https://github.com/rust-itertools/itertools/issues/768#issuecomment-1741780757, there is no attempt to run `cargo test --all-targets` in CI. Hey, I don't even know exactly what that even means. Apparently, it means running benchmarks, as well.

But... it wouldn't hurt, I suppose, to run the CI workflow on push to master, as well. As a confirmation that whatever did reach the default branch, is, in fact, healthy, just in case.

**Comment by Philippe-Cholet** [comment]
I just fixed the reported error in #770 (see details there). It was nearly nothing and definitely not an issue because benchmarks only run with `release` profile. I don't think we need to do anything more.
This was surprising, that's for sure.

**Comment by Philippe-Cholet** [comment]
@warren2k @mightyiam  Do you think we need to do anything more or should we close this?
Since a few days (more recent than this issue), we are using a "merge queue" which from my understanding of it is a bit better to guarantee the health of the default branch.

**Comment by mightyiam** [comment]
We never looked into the merge queue feature. We'll leave this decision up to you. Feel free to close the issue at your discretion.

**Comment by Philippe-Cholet** [comment]
Guarantee the health of the default branch is not a destination but a journey that we won't forget so I don't think we need this issue as a remainder (so I'm closing this).
Plus, CI has been quite improved lately, thanks to you both.
