### ISSUE TITLE
zip together an unknown number of iterators

### ISSUE THREAD

**Issue by wangjiawen2013** [rust-itertools/itertools#828]
Hi,
who can helps ?

https://stackoverflow.com/questions/55291961/how-can-i-zip-together-an-unknown-at-compile-time-number-of-iterators

https://stackoverflow.com/questions/29669287/how-can-i-zip-more-than-two-iterators

**Comment by Philippe-Cholet** [comment]
- https://docs.rs/itertools/latest/itertools/macro.izip.html
- https://docs.rs/itertools/latest/itertools/fn.multizip.html

**Comment by wangjiawen2013** [comment]
I want to zip columns of Polars dataframe, but sometimes there are a lot number of columns, I must put all the column names using izip! manually. It's very inconvinence.

**Comment by Philippe-Cholet** [comment]
I'm not familiar with Polars but "zip columns" is not just rows? in which case there sure is a method for it. Unless it's hidden behind the crate feature "rows" that you might need to add first (based on [this](https://docs.rs/polars/latest/polars/frame/row/struct.Row.html)).
