### ISSUE TITLE
How does tree_reduce achieve O(ln(n)) operations? 

### ISSUE THREAD

**Issue by rbruenig** [rust-itertools/itertools#946]
How does `Itertools::tree_reduce` achieve `O(ln(n))` operations? 

If we take the visualization from the documentation:

```
1 2 3 4 5 6 7
│ │ │ │ │ │ │
└─f └─f └─f │
  │   │   │ │
  └───f   └─f
      │     │
      └─────f
```

This looks like a full binary tree with `n` being the number of leaf nodes and the operations `f` being the internal nodes. A binary tree with `I` internal nodes has `L = I + 1` leaf nodes (if I'm not mistaken). That would mean the number of operations is always `n - 1`, which would be `O(n)` and the same as the normal `Iterator::reduce` operation.

What am I missing?

**Comment by Philippe-Cholet** [comment]
From what I understand myself, the compiler can better optimize heavy things (such as `|a, b| format!("{a}{b}")`) than with `reduce` where things are done in strict order. It can parallelize some things I suppose.

His author @scottmcm will have a better explanation than me though.

**Comment by rbruenig** [comment]
If parallelization is the main benefit, we should probably update the documentation, as it currently states:

> otherwise if f is non-trivial like format!, you should use tree_reduce since it reduces the number of operations from O(n) to O(ln(n))

**Comment by rbruenig** [comment]
Thanks for the answer! 

Could you elaborate on the example with `f` being `format!`? Isn't there a different `n` for `tree_reduce` and `format!`? For `tree_reduce` the `n` seems to be the number of elements that the iterator yields, for `format!` the `n` is either the number of arguments (which would be the same between `reduce` and `tree_reduce`) or the length of the given strings / the length of the result string.

The length of the arguments is different between `reduce` and `tree_reduce`, since for `reduce` one argument (the "accumulator") would constantly grow while the other one is always just the next element from the iterator. For `tree_reduce` both arguments grow. In the fist level of the tree all arguments are elements from the iterator, then results from the previous level and so on. For `format!("f({a}, {b})")` the result is different: `f(f(f(a, b), c), d)` vs `f(f(a, b), f(c, d))`. But the length of both results are the same, so the sum of all `n` given to format should be the same. Both variants do the same number of allocations (depends only on number of calls to `f`) and allocate the same number of overall bytes.

**Comment by rbruenig** [comment]
Thanks, that makes sense! That example would be super helpful in the documentation. If you'd like I could prepare a PR for updating the doc.

**Comment by Philippe-Cholet** [comment]
@rbruenig Do you want to make a PR?

**Comment by rbruenig** [comment]
@Philippe-Cholet I'll prepare one this week. Didn't get around to it last week.

**Comment by rbruenig** [comment]
@Philippe-Cholet @scottmcm  I provided a PR to update the documentation. Please let me know if it needs to be adapted 🙂
