### ISSUE TITLE
Implement `DoubleEndedIterator` for `FilterOk`

### ISSUE THREAD

**Issue by Xenira** [rust-itertools/itertools#947]
Should be doable with `rfind` unless there is a reason I overlooked.

Would be willing to implement this.

**Comment by Philippe-Cholet** [comment]
`FlattenOk`, `MapSpecialCase` (for `MapOk`, `MapInto`) are double ended and `ProcessResults` since a few weeks.
`FilterOk` and `FilterMapOk` are not (yet) but it seems reasonable to me.

**Comment by Xenira** [comment]
Like that? Have to admit, not entirely comprehending the test system yet.

**Comment by Philippe-Cholet** [comment]
@Xenira I did not notice they were not double ended so thanks for this.
