### ISSUE TITLE
Do we need a `rfind_map`?

### ISSUE THREAD

**Issue by Xenira** [rust-itertools/itertools#949]
While implementing `DoubleEndedIterator` for `FilterMapOk` i stumbled over the `find_map` in the `Iterator`'s `next` implementation.
The most straight forward way to implement `next_back` would be to just inverse that, but `rfind_back` does not exist.

Would that be something itertools could need?

**Comment by Philippe-Cholet** [comment]
I think the std lib dismissed the idea, probably not more efficient than the alternative. I don't know where to find the info though.

The only think related I have is https://github.com/rust-itertools/itertools/pull/818#discussion_r1425902068 where we had the same thought.

Is it really missing though?

**Comment by Xenira** [comment]
Just struck me as odd, that there is `find_map` and no `rfind_map`. But guess `rev()` works fine as well and keeps the trait concise.

**Comment by Xenira** [comment]
Well, maybe a bit constructed, but `rall` and `rany` could make sense if you know elements are not evenly distributed and the iterator may short circuit earlier :P
