### ISSUE TITLE
`maybe_` for `cmp`, `partial_cmp`, `eq`, `ne`, `lt`, `le`, `gt`, `ge`

### ISSUE THREAD

**Issue by Xenira** [rust-itertools/itertools#952]
Grouped this together, as those methods all take a second iterator (or `IntoIterator` to be precise) with `Ord` item as argument.

Having results would require something like this (if that even works, did not test yet):

```rust
iter.process_results(
     |iter| other.process_results(|other| iter.ge(other))
)??,
```

Having `maybe_` methods would make this way less verbose and the intent clearer.

Related to #844 and label [![GitHub labels](https://img.shields.io/github/labels/rust-itertools/itertools/fallible-iterator)](https://github.com/rust-itertools/itertools/issues?q=is%3Aissue+is%3Aopen+label%3Afallible-iterator)

**Comment by Philippe-Cholet** [comment]
I personally don't know where those `cmp` & Co. methods are used. I never did myself (but I'm no veteran). So I don't know if there is a need for 8 `maybe_` methods, especially when no one asked for `cmp_ok` or related (we have a few `_ok` methods).

**Comment by Xenira** [comment]
Don't have a concrete usecase as well. Kind wanted to support it as a lib function. Can be closed until someone has a real usecase.
