### ISSUE TITLE
Add single-element tuple for `collect_tuple`

### ISSUE THREAD

**Issue by amab8901** [rust-itertools/itertools#953]
I'm trying to select exactly one element via `let the_one = vector.iter().filter(|item| item == condition).collect_tuple()`. It needs to match exactly one element, no more, no less. If 2 elements are in the iterator after the filter, then that's an error (due to ambiguity on which item to use later in the code). 

The `.first()` and `.last()` and `.next()` methods on iterators don't work because they don't guarantee that there's only one element in the vector/iterator.

**Comment by Philippe-Cholet** [comment]
What about `Itertools::exactly_one`?

**Comment by phimuemue** [comment]
For the sake of completeness: 1-element tuples are [supported, but you may need type annotations](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9b86c69c62eaf918a05a70c4c1c42bec):

```
    let vector = vec![1,2,3,4];
    let the_one : Option<(_,)> = dbg!(vector.iter().filter(|item| **item >= 2).collect_tuple());
    //                     ^
    //                     |
    //                     +-- Note the comma to signify a 1-element tuple.
```
