### ISSUE TITLE
Increase MSRV to 1.63

### ISSUE THREAD

**Issue by jswrenn** [rust-itertools/itertools#959]
This will allow us to progress on https://github.com/rust-itertools/itertools/labels/const-generics, particularly #560. This entails:
- updating
  https://github.com/rust-itertools/itertools/blob/a0225ceee50cafe9e974699e1cbf7fa9a1dcf901/.github/workflows/ci.yml#L47
- updating 
  https://github.com/rust-itertools/itertools/blob/a0225ceee50cafe9e974699e1cbf7fa9a1dcf901/Cargo.toml#L19
- updating
  https://github.com/rust-itertools/itertools/blob/a0225ceee50cafe9e974699e1cbf7fa9a1dcf901/src/lib.rs#L49
- auditing for `allow`'d clippy lints that can now be fixed 
- auditing `TODO` comments that can now be fixed

**Comment by Philippe-Cholet** [comment]
@kinto-b That's something you might want to do.
The "big" part here is to `grep clippy` and see which lint(s) can be resolved, if any.

**Comment by kinto-b** [comment]
@Philippe-Cholet Sure thing :) I assume you mean, go through and see which `#[allow(clippy::*)]` can be dropped?

Shall I also action the TODOs such as https://github.com/rust-itertools/itertools/blob/a0225ceee50cafe9e974699e1cbf7fa9a1dcf901/src/concat_impl.rs#L22-L29

**Comment by jswrenn** [comment]
Yes, please do!
